const SUCCESS = 200;
const CREATED = 201;
const INVALID_DATA = 422;
const INTERNAL_SERVER_ERROR = 500;
const MIN_STR_LENGTH = 5;
const MIN_ID_LENGTH = 24;

module.exports ={
  SUCCESS,
  CREATED,
  INVALID_DATA,
  MIN_STR_LENGTH,
  INTERNAL_SERVER_ERROR,
  MIN_ID_LENGTH
};
