module.exports = {
  HTTP_OK_STATUS: 200,
  HTTP_CREATED_STATUS: 201,
  HTTP_BAD_REQUEST_STATUS: 400,
  HTTP_AUTHENTICATION_NEGATED_STATUS: 401,
  HTTP_NOT_FOND_STATUS: 404,
  HTTP_UNPROCESSABLE_ENTITY_STATUS: 422,
  HTTP_INTERNAL_SERVER_ERROR_STATUS: 500
};
